### ISSUE TITLE
Wrong email at login is creating server error in UserDao

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [tagaprice/tagaprice#27] opened 2011-05-21 17:46 UTC
if user is not available in the DB,  the UserDao should return false or a NoUserException. 
Now i get a 500 server error

**Comment by reihu** [comment] 2011-06-15 22:04
Actually that was not an issue in the DAO but a NullPointerExeption caused by a missing check in LoginServiceImpl.setLogin().
The issue has been fixed in commit 06fe2ede81be69e55049

**Closed as completed by reihu** 2011-06-15 22:04 UTC
Labels: 4 - High, Server
